### ISSUE TITLE
Kill ec2 if agent is lost

### ISSUE THREAD

**Issue by juandiegopalomino** [buildkite/elastic-ci-stack-for-aws#1051]
<img width="1353" alt="Screen Shot 2022-09-21 at 3 26 41 PM" src="https://user-images.githubusercontent.com/10430635/191621331-cdc540c8-aa8c-42a0-9ea6-2e1656eaf360.png">

**Comment by triarius** [comment]
Hi @juandiegopalomino. Currently, the design of the [buildkite-agent-scaler](https://github.com/buildkite/buildkite-agent-scaler) is that it only changes the `DesiredCount` of the ASG for the elastic stack. It does not have the ability (or IAM permissions) to terminate a specific instance. Modifying it so that it does is probably something that would need to be redesigned from the ground up, and that's not on our roadmap to do that at this stage.
