### ISSUE TITLE
v5.13.0 stack is not accessible

### ISSUE THREAD

**Issue by nicwise** [buildkite/elastic-ci-stack-for-aws#1063]
URL: https://s3.amazonaws.com/buildkite-aws-stack/v5.13.0/aws-stack.yml
Release: https://github.com/buildkite/elastic-ci-stack-for-aws/releases/tag/v5.13.0

![image](https://user-images.githubusercontent.com/127924/201755709-4a81d323-16a0-4ed9-ae76-9ba6808d5eba.png)

I've seen this happen quite a lot. Can you fix your CI process to set the ACLs? Maybe use some tool like Buildki.... oh wait.... :) 

@DrJosh9000

**Comment by DrJosh9000** [comment]
Whoops! This is my first time releasing, so there's a strong chance I've missed something. I'll investigate.

**Comment by DrJosh9000** [comment]
I've re-run the pipeline that is supposed to publish the stack. (It failed because of a timeout, and yesterday I was busy looking at a different run that succeeded when I published the release here.) Looks like https://s3.amazonaws.com/buildkite-aws-stack/v5.13.0/aws-stack.yml is now working. Can you give it a go?

**Comment by nicwise** [comment]
also #hugops and well done on your first release :)
