### ISSUE TITLE
Docs do not include a migration path off of SpotPrice

### ISSUE THREAD

**Issue by ianwremmel** [buildkite/elastic-ci-stack-for-aws#1224]
**Describe the bug**

I'm attempting to update from v5.11.1 to v6.7.1 and the removal of `SpotPrice` is a major road block.

I had set `SpotPrice` to be the same as the on demand price in my region to ensure I never spend more on spot than I would if I were using on demand. With the new template, it's not clear to me (1) how to ensure I don't pay more than the on demand price or (2) how to even use spot instances.

I _think_ 1 is currently impossible while 2 might be doable by setting `OnDemandPercentage` to `0`. 

Ideally, it'd be nice to be able to supply missing demand using OnDemand instances when Spot are not available (either because there's no capacity or because the spot price is above the OnDemand price), but that's more of a nice to have than a requirement.

**Steps To Reproduce**

Search for documentation on spot pricing.

**Expected behavior**

Find documentation on spot pricing. 

**Actual behaviour**

There was no documentation for spot pricing.

**Stack parameters (please complete the following information):**
 - AWS Region: us-east-1
 - Version: v6.7.1

**Additional context**

I'm a bootstrapper, so I'm particularly price-sensitive.

**Comment by DrJosh9000** [comment]
Hi @ianwremmel ! Thanks for raising this. 

On (2), that looks correct: because the underlying `OnDemandBaseCapacity` parameter defaults to 0, then setting `OnDemandPercentage` to 0 should mean 100% Spot instances.

I can see why [the change to remove `SpotPrice`](https://github.com/buildkite/elastic-ci-stack-for-aws/pull/1130) might be contentious. This has been discussed in the past: one recurring point is whether it is better to allow CI/CD jobs to be terminated because the spot price is more expensive than the configured maximum, or to allow the jobs to finish (avoiding wasting engineer time). Because of either max price interruption, or because of Spot unavailability, we've felt that it's not a great experience for our customers to rely on Spot for this.

Other cost optimisations could be to enable `BuildkiteTerminateInstanceAfterJob`, adjusting `ScaleInIdlePeriod`, or tweaking the `SpotAllocationStrategy` ([AWS recommend `price-capacity-optimized`](https://docs.aws.amazon.com/autoscaling/ec2/APIReference/API_InstancesDistribution.html)).

Another issue tracking the idea to use OnDemand when Spot is unavailable is here: https://github.com/buildkite/elastic-ci-stack-for-aws/issues/851
