### ISSUE TITLE
Better cloudformation stack updates

### ISSUE THREAD

**Issue by sgringwe** [buildkite/elastic-ci-stack-for-aws#150]
Right now updating a cloudformation stack is quite buggy and (for me) almost always fails. Even something as simple as updating the spot price for instances is not possible.

As a workaround, we end up creating a new stack and deleting the old one. This is error prone, requires access to API keys, results in failed builds, and is time consuming.

Preferably the process for the cloudformation updates is not as buggy. Unfortunately I have no recommendations on how to improve this at this time.

**Comment by gugahoi** [comment]
I haven't had any problems updating the stack

**Comment by lox** [comment]
Can you provide some more info on what fails during updates?

**Comment by ahawkins** [comment]
I've had problems recently which I believe are related to race conditions between scaling actions caused by CloudFormation update and changes in the job queue. The end result is that it may fail. I've started to scale the existing stack down to zero before doing any update. This reduces the possibility for certain failure modes.

**Comment by lox** [comment]
I think that is very sensible @ahawkins. We should document this in https://github.com/buildkite/elastic-ci-stack-for-aws#updating-your-stack.

**Comment by lox** [comment]
We've recently made some changes that will improve reliability of updates, specifically around suspending auto-scaling during them. Let us know if these issues persist!
