### ISSUE TITLE
Alternative to cloudformation

### ISSUE THREAD

**Issue by KevinGrandon** [buildkite/elastic-ci-stack-for-aws#246]
Our security policy prevents us from using cloudformation to deploy an elastic stack due to strict iam resourcing control.

We're currently using Terraform and would love to have an alternative to cloudformation to setup the elastic stack.

**Comment by lox** [comment]
Thanks for the issue @KevinGrandon, Terraform is absolutely something we are considering. Will discuss this some more and update shortly.

Would it be possible to provide more detail on CloudFormation? Does "strict iam resourcing control" rule out ANY CloudFormation, or are there things about how we are using that are problematic? Would it be possible for us to address these security concerns and let you move forward with CloudFormation? Many folks have been wrapping it in a Terraform resource: https://www.terraform.io/docs/providers/aws/r/cloudformation_stack.html

**Comment by lox** [comment]
We could for instance lock down the permissions to only work in the provided vpc / subnets:

https://aws.amazon.com/blogs/security/how-to-help-lock-down-a-users-amazon-ec2-capabilities-to-a-single-vpc/

**Comment by lox** [comment]
@toolmantim did you have any other insight into this one?

**Comment by SomeoneWeird** [comment]
@KevinGrandon how does Cloudformation differ to Terraform?

**Comment by lox** [comment]
Do you mean in so far as it's security implications?

**Comment by toolmantim** [comment]
I don't have any more insight I'm afraid!

I know @pvdvreede is ingesting this via Terraform. Have you had any luck?

**Comment by SomeoneWeird** [comment]
@lox Yeah. You should just be able to create an IAM user with the necessary permissions and then execute CF as that user. I'm not seeing what else terraform would do, seeing as it would obviously use a subset of IAM

**Comment by pvdvreede** [comment]
We are using Terraform as a wrapper around the Cloudformation. In Terraform we create a IAM policy and then pass that policy into the Cloudformation. However, the Cloudformation still creates the instance profile, role and then attaches this extra policy. 

Would passing an IAM Role into the Cloudformation so that it only creates the instance profile, and connects it to the passed in Role help with your Security restrictions, @SomeoneWeird ?

**Comment by SomeoneWeird** [comment]
@pvdvreede I think you mean @KevinGrandon there :)

**Comment by lox** [comment]
I'd guess the issue here is the broad permissions that would be required for the stack in it's present form. It needs IAM creation for one, which is basically root access. We could look at locking this down, but I'd want to know if @KevinGrandon has other requirements beyond that.

**Comment by pvdvreede** [comment]
Ahh, yes sorry I did mean @KevinGrandon !

**Comment by KevinGrandon** [comment]
I think that locking down IAM permissions would be a good step and allow many larger companies to consider using this stack in the first place. For us, we have a requirement to deploy this with Terraform so we're going to start investigating using that.

**Comment by gugahoi** [comment]
@KevinGrandon Just to be sure I understand what you mean by `strict iam resourcing control`: the roles/users you have access to are excluded from using the cloudformation service altogether? Or is it a resource created by the stack the blocks you? 

If it's the former than I don't understand how Terraform will help you as it will be making calls into cloudformation - unless you dissect the stack into it's base components.

**Comment by KevinGrandon** [comment]
Yes, I don't think we're going to be able to use Cloudformation at all currently. It sounds like we're probably going to have to use base components for the time being. Has anyone successfully done that?

**Comment by gugahoi** [comment]
At one point I started trying to convert the stack to Terraform but it would be too much work to consume any updates so I decided to just consume the stack.

**Comment by wbotelhos** [comment]
Hi, could someone done the setup with Terraform/Packer?

I would to try Buildkit service, but I don't want to introduce Cloudformation on my AWS account.

Any chance for this support or at least a complete tutorial of what is required for, @lox ?

**Comment by lox** [comment]
@wbotelhos it would be a complete rewrite to exclude CloudFormation @wbotelhos, so not something we've looked at. 

You can manage the CloudFormation resources with Terraform though!

**Comment by tduffield** [comment]
Here's an example of how we manage Buildkite with Terraform:

```terraform
resource "aws_cloudformation_stack" "buildkite_<QUEUE_NAME>" {
  name = "buildkite-<QUEUE_NAME>"

  parameters {
    KeyName                        = "XXXXXXXXXXX"
    BuildkiteAgentRelease          = "stable"
    BuildkiteAgentToken            = "XXXXXXXXXXXXXXX"
    BuildkiteAgentTags             = "os=linux"
    BuildkiteQueue                 = "<QUEUE_NAME>"
    AgentsPerInstance              = 4
    SecretsBucket                  = "XXXXXXXX"
    ArtifactsBucket                = ""
    BootstrapScriptUrl             = "s3://XXXXXXXXXXX/buildkite_boot.sh"
    VpcId                          = "XXXXXXXX"
    Subnets                        = "XXXXXXXXXX"
    AvailabilityZones              = ""
    InstanceType                   = "c5.2xlarge"
    SpotPrice                      = "0"
    MaxSize                        = 40
    MinSize                        = 0
    ScaleUpAdjustment              = 3
    ScaleDownAdjustment            = -1
    ScaleDownPeriod                = 1800
    RootVolumeSize                 = 250
    SecurityGroupId                = "sg-XXXXXXX" 
    ImageId                        = ""                                                        # use default
    ManagedPolicyARN               = "arn:aws:iam::XXXXXXXXXXXX:policy/XXXXXXXXXXXX"
    ECRAccessPolicy                = "none"
    AssociatePublicIpAddress       = "false"
    EnableSecretsPlugin            = "true"
    EnableECRPlugin                = "false"
    EnableDockerLoginPlugin        = "true"
    EnableDockerUserNamespaceRemap = "true"
    EnableCostAllocationTags       = "true"
    CostAllocationTagName          = "X-Application"
    CostAllocationTagValue         = "buildkite"
  }

  template_url = "https://s3.amazonaws.com/buildkite-aws-stack/v${var.elastic_ci_stack_version}/aws-stack.json"
  capabilities = ["CAPABILITY_IAM", "CAPABILITY_NAMED_IAM"]
}
```

**Comment by wbotelhos** [comment]
Thanks for your answer @lox .
Thanks for the template @tduffield :)

**Comment by lox** [comment]
No worries! One day we'll get a pure Terraform alternative happening!

**Comment by ianwremmel** [comment]
If anyone comes across this, it looks like `template_url = "https://s3.amazonaws.com/buildkite-aws-stack/v${var.elastic_ci_stack_version}/aws-stack.json"` doesn't quite work anymore. specifically, I `latest` is the only value I can find for `v${var.elastic_ci_stack_version}` that doesn't return access denied.

**Comment by ianwremmel** [comment]
update on my previous comment: it appears part of my issue was using `aws-stack.json` rather than `aws-stack.yml`.

**Comment by nitrocode** [comment]
A reusable terraform module would be more convenient than CF so we can keep the entire IAM role, attached managed policies, and inline policies all in code.

At the moment, we run the bk cluster and attach policies to the role in terraform.

**Comment by bshelton229** [comment]
I'm going to take a crack at a native terraform module here - https://github.com/roverdotcom/terraform-aws-buildkite-elastic-ci-stack. I think a separate repo will work the best if it eventually wants to end up on the terraform public registry. I'll try to get a proof of concept up and running.

The cloudformation from this repo has worked really well for us so far, but we're also a 100% terraform shop, and it seems like there is interest in a native terraform solution. We're currently applying the cloudformation stack via terraform, but our interest in seeing mixed instance types in the ASG for spot (as mentioned in #651) has led us to thinking about a native terraform solution.

Hopefully I can have a proof of concept going in a week or so if all goes well. I'm planning on basing it off of the current stable v4.5.0 stack, only supporting the native lambda scaling. There may be some tricks to pinning the lambda and ami resources properly in a separate project, but I think I have some ways to get it working initially. I'll circle back when I have something if folks are interested.

**Comment by yob** [comment]
@bshelton229 sounds good, we'll be interested to see how it goes!

> only supporting the native lambda scaling

Our intention is to make this the primary scaling method in future releases, so this is a good choice.

**Comment by bshelton229** [comment]
I got a chance to get a proof of concept of a pure terraform module working in our test environment. We're going to go that direction for our shop for sure, and as it seems there is interest in a terraform module, I'm planning on publishing the module to an open source repo. I decided to base off of what's landing in master because there is some great stuff in there. Overall the AMI component built from this repo, and the autoscaling lambda published to s3, are easy to use to get a terraform stack working. The new autoscaler lambda is absolutely amazing, and we like how the SSM parameter holding the agent token is handled in master. I'll be starting on this next week and wanted to get some feedback if possible.

My main concern is staying up to date with the [inputs to the cloudinit script](https://github.com/buildkite/elastic-ci-stack-for-aws/blob/master/templates/aws-stack.yml#L877) used by the AMI built in this repo. If we start relying on this interface in external projects, it might be nice to document the env var inputs and maybe publish a changelog? There is one non-breaking issue with needing to pass `BUILDKITE_STACK_NAME`, which is required, and used for `cfn-signal`. Thankfully it exists OK right now, but if we start using this outside of cloudformation more formally, maybe we could check for that var being empty and not send `cfn-signal`?

I'm initially planning on creating a single terraform module that would act like the cloudformation stack, but would be composed of several modules that could also be used independently if desired. You would be able to either use the higher level module directly, getting a full stack experience, or you would be able to reach into the sub-components yourself and build your own stack. The component modules would likely be things like `autoscaler-lambda`, `asg`, `iam-role`, `secrets-bucket`, `userdata`. At the higher level, selectively using or not using entire sub-modules is finally much easier in terraform `0.13`. I'd love feedback as to whether or not folks would want something that worked with terraform `0.12` as well. As soon as I have something that is more generally consumable I'll post back here.

**Comment by nitrocode** [comment]
@tduffield thanks a lot for sharing this.

We were going to wait on an official terraform module but we figured it might take a while for an official (or unofficial) one to get traction.

This is what we did

1. Create an internal module with every parameter as it's own input variable
1. Override the default values from the cf stack with our own values
    * if we don't have an override value then reuse the default from the stack
1. Take an input for the version with a default of `v5.0.0` so it can be overridden with `latest` or `master`
1. Version the terraform module itself
1. Output all the stack outputs. The useful one is the IAM role name so additional inline and managed policies can be easily attached
1. Make sure `disable_rollback=true` or the imported stack will need to be deleted and recreated instead of updated

This solution works for us but allowing us to not have to copy around Makefiles or shell scripts around different repos and allows bk iam policies to be coupled with the queue.

The only issue I've noticed so far is that when importing into terraform, it doesn't copy the parameters correctly in the state so it will need to be applied (which results in a cloud formation update if disable rollback is true) before parameter differences can be seen. I created a ticket with the aws provider here https://github.com/hashicorp/terraform-provider-aws/issues/15992.

This should also have the way forward for terraforming build pipelines in the future.

**Comment by nitrocode** [comment]
@tduffield thanks a lot for sharing this.

We were going to wait on an official terraform module but we figured it might take a while for an official (or unofficial) one to get traction.

This is what we did

1. Create an internal module with every parameter as it's own input variable
1. Override the default values from the cf stack with our own values
    * if we don't have an override value then reuse the default from the stack
1. Take an input for the version with a default of `v5.0.0` so it can be overridden with `latest` or `master`
1. Version the terraform module itself
1. Output all the stack outputs. The useful one is the `InstanceRoleName` so additional inline and managed policies can be easily attached.
    ```hcl
    output "InstanceRoleName" {
      value = try(aws_cloudformation_stack.buildkite_queue.outputs.InstanceRoleName, "")
    }
    ```
1. Make sure `disable_rollback=true` on the `aws_cloudformation_stack` or the imported stack will need to be deleted and recreated instead of updated.

This solution works for us by preventing us from copying around Makefiles or shell scripts to different repos and allows bk iam policies to be coupled with the queue. It gives us a single point of truth for sane defaults while allowing us to easily bump up versions. Only thing required would be bumping the version of the module reference source (if the HEAD of the branch is not used) and a subsequent reapply.

The only issue I've noticed so far is that when importing into terraform, it doesn't copy the parameters correctly in the state so it will need to be applied (which results in a cloud formation update if disable rollback is true) before parameter differences can be seen. I created a ticket with the aws provider here https://github.com/hashicorp/terraform-provider-aws/issues/15992 (please upvote if possible).

This should also have the way forward for terraforming build pipelines in the future. 
 
```hcl
provider "aws" {
  region = "us-west-2"
}

module "buildkite_queue" {
  # this can and should be pinned to a release tag using ?ref=tags/x.y.z
  source = "git@github.com:company/buildkite-elastic-ci.git//terraform?ref=main"
 
  # tag buildkite queue with team
  team = "my_team"
  # queue name
  BuildkiteQueue = "bananafanadingdong"
}
 
# Example: attach an inline-policy to the queue
 
## define the inline-policy
 
data "aws_iam_policy_document" "my_new_really_super_duper_cool_and_secure_iam_policy" {
  statement {
    effect    = "Allow"
    resources = ["*"]
 
    actions = [
      "ec2:DescribeTags"
    ]
  }
}
 
## attach the above inline-policy to the buildkite role from cloudformation
 
resource "aws_iam_role_policy" "test_policy" {
  name = "my_new_really_super_duper_cool_and_secure_iam_policy"
  role = module.buildkite_queue.InstanceRoleName
 
  policy = data.aws_iam_policy_document.my_new_really_super_duper_cool_and_secure_iam_policy.json
}
 
# Example: attach a managed IAM policy to the queue
 
resource "aws_iam_role_policy_attachment" "secrets_access" {
  role       = module.buildkite_queue.InstanceRoleName
  policy_arn = "arn:aws:iam::1234567890:policy/secrets-access"
}
```

**Comment by keithduncan** [comment]
A terraform stack isn’t on our roadmap currently, and supporting two independent AWS Elastic CI Stack implementations that offer the same functionality isn’t something we can reasonably commit to right now 😓

It may be that we end up with enough sufficiently compelling reasons to switch to terraform and do a re-write here, but we aren’t at that stage yet 😅 It may also be that ancillary efforts to component-ise the existing stack, like moving the Lambda scaler to the Serverless Application Repository, or potentially breaking out AMI building, may ease such a transition or make bootstrapping a community implementation more viable!

Speaking to the original issue of security policy preventing the use of CloudFormation, if still applicable, I would suggest looking into AWS Organisation Service Control Policies and IAM Permission Boundaries. These enable tight scoping of permissions and can limit the API actions CloudFormation can perform inside an account. These combined with using an isolated AWS Account may enable an acceptable use of CloudFormation.

**Comment by ianwremmel** [comment]
@keithduncan I think that's a fair decision, but I have one proposal that might be a fairly small added surface area for you with a lot of benefit for the rest of us. I've been using the solution in https://github.com/buildkite/elastic-ci-stack-for-aws/issues/246#issuecomment-399426091 pretty successfully, but the annoying part is updating the parameters each time there's a new version and the stack's variables change. Would you consider publishing a terraform module (_not_ a provider) that simply wraps the stack template and exposes each parameter as a module variable?

**Comment by keithduncan** [comment]
> Would you consider publishing a terraform module (_not_ a provider) that simply wraps the stack template and exposes each parameter as a module variable?

I’ve published a quick spike in this direction as a [gist](https://gist.github.com/buildkite-elastic-stack-releaser/6e5a51eaed8e6be2602cefe1eb3285fc) that will wrap a CloudFormation template with a terraform JSON template and expose module `variable`s for each template `Parameter`.

This is not an official or supported project! 😅  I have only tested this with the latest version of the Elastic CI Stack for AWS template and successfully ran a `terraform plan` and `apply` for the generated module.

I hope this is useful for folks, if it is please do let us know.

**Comment by nitrocode** [comment]
@keithduncan that's basically what we are doing now. we have private modules that l wrap the cloud formation stack with the terraform resource. this works well but, like @ianwremmel said, if there's a new version with a new input, then we need to create a new input and update the module.

if there was an official terraform module maintained by buildkite within an official repo and updated upon each release (change of inputs), then we could stop having to maintain our private modules and instead point our code to the upstream official module.

**Comment by eleanorakh** [comment]
Yea @nitrocode, I can absolutely see the value in that! I've added it to the backlog for us to tackle as the year kicks off.
