### ISSUE TITLE
Can't update stack due to VPC/AZ error

### ISSUE THREAD

**Issue by bjeanes** [buildkite/elastic-ci-stack-for-aws#319]
Whenever I try to update from v2.0.2 to v2.1.4 and changing no settings, the update always rolls back with:

> CIDR Block must change if Availability Zone is changed and VPC ID is not changed

My stacks never specified VPCs or AZs (as these fields were optional, and I don't know enough to make intelligent decisions here anyway).

Am I doing something wrong?

**Comment by bjeanes** [comment]
Correction: 2/3 fail (consistently). One seems to be upgrading correctly:

**Comment by bjeanes** [comment]
(FWIW, I just destroyed the stacks and re-created)

**Comment by lox** [comment]
Urgh this is the worst. Would you believe that the Availability zones change over time, so the results of `Fn::GetAZs` change and cause this error? 

The workaround is to figure out what your Availability Zones are (you can look at the subnets created by the old stack) and then pass these in as the `AvailabilityZones` param. 

I ran into exactly this bug with https://github.com/buildkite/elastic-stack-updater. Will leave this open as a TODO for an FAQ or docs.

**Comment by bjeanes** [comment]
> The workaround is to figure out what your Availability Zones are (you can look at the subnets created by the old stack) and then pass these in as the AvailabilityZones param.

Good to know for the future. Thanks!

**Comment by keithduncan** [comment]
:wave: @bjeanes 😄

I can’t find a recent occurrence or any updated guidance from Amazon on how to handle it. Perhaps the `!GetAZs` function call returns more stable results since this happened 🤷🏻‍♂️ It’s also possible the [Default VPC subnets](https://github.com/buildkite/elastic-ci-stack-for-aws/issues/41#issuecomment-872022978) in your account were changed between deployments resulting in this error, but since one stack failed but the others didn’t that seems unlikely too 🤔

If it comes up again we’ll dig into it some more 🙇‍♂️
