### ISSUE TITLE
Lambda scaler: instances with multiple agents scaled-in on inactivity

### ISSUE THREAD

**Issue by uriahcarpenter** [buildkite/elastic-ci-stack-for-aws#587]
We run multiple copies for this stack for different scenarios and I noticed the configurations where `AgentsPerInstance > 1`, and using the Lambda scaler, some instances would only have a single agent registered on buildkite.com. But both agents would be registered immediately after the instance was started.

Reading the agent logs shows the culprit: `Agent has been idle for 1800 seconds` and clearly shows terminating one of the agents on the instance. The single agent left on the instance operates properly. Switching back to the ASG scaler corrects this incorrect scale-in behavior.

Attaching my CloudFormation config and agent logs.

<img width="1694" alt="lambda-scaler-agent-scale-logs" src="https://user-images.githubusercontent.com/474506/57962189-f1b63f80-78d9-11e9-9082-0bf9a504a3bb.png">
<img width="1149" alt="lambda-scaler-cf-config" src="https://user-images.githubusercontent.com/474506/57962190-f24ed600-78d9-11e9-8f7d-ca476593318c.png">

**Comment by jeremiahsnapp** [comment]
This issue was reported here https://github.com/buildkite/agent/issues/985

There ended up being a few other timeout related issues that also needed to be fixed. The latest buildkite-agent release 3.12.0 has fixed all of these issues.

The agent version in the elastic-ci-stack-for-aws repo has recently been bumped up to 3.12.0 https://github.com/buildkite/elastic-ci-stack-for-aws/pull/590 so you can either continue to use the ASG scaler until a new version of elastic-ci-stack-for-aws has been released or you can use the cloudformation stack available for the recent commit that added buildkite-agent 3.12.0.

`https://s3.amazonaws.com/buildkite-aws-stack/master/705cc59a837d7e6cb7fa97ffe8584af8537979f3.aws-stack.yml`

**Comment by lox** [comment]
I'll put out a point release of the 4.x series with the new version of the agent in it.

**Comment by lox** [comment]
https://github.com/buildkite/elastic-ci-stack-for-aws/releases/tag/v4.3.3
