### ISSUE TITLE
[Feature request] add support to minimum 0 instance

### ISSUE THREAD

**Issue by ailisp** [buildkite/elastic-ci-stack-for-aws#672]
Currently minimum 0 instance doesn't work because when there's no buildkite agent, it cannot receive signal from buildkite.com, and make request to aws to scale up. However running a single instance empty can be expensive too (I'm running m5.8xlarge). It would be great to have a tiny, separate from elastic ci stack instance or container (can be manually configured) to talk to aws to scale up from 0 instance.

**Comment by chloeruka** [comment]
Hi @ailisp – 0 should already be a supported minimum in the stack! What will happen in this case is that the ASG will not start with any instances, but a lambda will continue to poll the Buildkite platform for your queue every minute. If you have any pending jobs on that queue, the lambda should launch new instances to meet demand. Depending on your stack configuration, this may work with a Cloudwatch alarm instead of a lambda. If this isn't working properly for you, please flick us an email at [support@buildkite.com](mailto:support@buildkite.com) with more information and we can have a look at what the issue might be.

**Comment by ailisp** [comment]
Yeah figured out it works later, just took longer to spin first instance so it's less useful
