### ISSUE TITLE
Update version of docker-compose on agent

### ISSUE THREAD

**Issue by zermatt** [buildkite/elastic-ci-stack-for-aws#689]
Hi, would it be possible to update the version of docker-compose baked into the agent, so the latest version of the compose file format (`3.8` at time of writing) is supported. thanks.

**Comment by chloeruka** [comment]
I'll consider this along with #688 this week alongside any relevant core Docker updates. 

We're currently using Docker Compose `1.25.1`:
https://github.com/buildkite/elastic-ci-stack-for-aws/blob/04c0ced472e0845173ab955735461b90b125ae10/packer/linux/scripts/install-docker.sh#L4-L6

This would be a huge jump, but we also haven't updated this dependency since 2018 so it might be worth reviewing.

**Comment by chloeruka** [comment]
Ah; whoops, now I realise you meant the file format version which is separate from the compose version – this looks like a pretty straightforward update from current to `>1.25.5` to support file format 3.8. I'll probably bump us to latest (`1.26.2`) and see how we get on.

**Comment by yob** [comment]
This was completed in #694
