### ISSUE TITLE
Install terminal-to-html on the agents

### ISSUE THREAD

**Issue by vgrigoruk** [buildkite/elastic-ci-stack-for-aws#693]
It would be very convenient if https://github.com/buildkite/terminal-to-html is installed on ec2 agents and available in PATH. Right now we're installing it manually in agent bootstrap script (which is ok as a workaround) like this:

```
TERMINAL_TO_HTML_VERSION=3.3.0
TERMINAL_TO_HTML_BINARY_NAME="terminal-to-html-$TERMINAL_TO_HTML_VERSION-linux-amd64"
TERMINAL_TO_HTML_TARBALL_NAME="$TERMINAL_TO_HTML_BINARY_NAME.gz"
TERMINAL_TO_HTML_TARBALL_URL="https://github.com/buildkite/terminal-to-html/releases/download/v$TERMINAL_TO_HTML_VERSION/$TERMINAL_TO_HTML_TARBALL_NAME"
EXPECTED_BINARY_SHA=91c0a56f6b3b573e1b728d17ed888d567c0256968180e7edc56532f717a0a29c

pushd /tmp && \
  wget "$TERMINAL_TO_HTML_TARBALL_URL" && \
  gunzip "$TERMINAL_TO_HTML_TARBALL_NAME" && \
  popd
  
ACTUAL_BINARY_SHA=$(openssl dgst -sha256 /tmp/$TERMINAL_TO_HTML_BINARY_NAME | cut -d' ' -f2)

if [ "$ACTUAL_BINARY_SHA" = "$EXPECTED_BINARY_SHA" ]; then
  mv /tmp/$TERMINAL_TO_HTML_BINARY_NAME /usr/local/bin/terminal-to-html
  chmod +x /usr/local/bin/terminal-to-html
else
  echo "$TERMINAL_TO_HTML_BINARY_NAME checksum $ACTUAL_BINARY_SHA does not equal $EXPECTED_BINARY_SHA" && exit 1
fi
``` 

I can contribute with a PR if this could be useful for more users.

**Comment by chloeruka** [comment]
Installing additional tooling in bootstrap as you've done is generally good practice. Another option would be to build your own AMI on top of the buildkite-agent AMI. 

As for terminal-to-html, usually we don't add additional tooling to the agent in order to keep it lean and portable, but I'd be really tempted to add it as a pre-installed tool as it is so small and it's [referenced in our docs](https://buildkite.com/docs/agent/v3/cli-annotate#supported-css-classes-colored-console-output). I'll ask around and see if this is something we have an appetite to include. If you did have time for building a PR to do this, that would make a pretty good case for its inclusion.

**Comment by vgrigoruk** [comment]
We're using the package to generate annotations from `git diff` output of 2 SQL files, which is not handled very nicely out of the box. 

After lots of attempts, we ended up with this shell command, which generates a nicely-looking annotation in Buildkite UI:

```
echo '<details><summary>DB schema diff</summary><pre class="term">' ; cat diff.sql | terminal-to-html | sed 's/-/\&#45;/g' ; echo "</pre></details>") | buildkite-agent annotate --style 'error' --context 'schema-diff'
```

**Comment by vgrigoruk** [comment]
Also, we ended up building our internal AMI, so the issue is not critical to us at all.

**Comment by keithduncan** [comment]
Hi @vgrigoruk, thank you for opening this issue 😄 With this since added to your own AMI build process and no subsequent requests to install this in our base image I’m going to go ahead and close this.
