### ISSUE TITLE
Adjusting AgentsPerInstance

### ISSUE THREAD

**Issue by nitrocode** [buildkite/elastic-ci-stack-for-aws#715]
To lower the number of instances that come up, it would be nice to know a recommended AgentsPerInstance per cpu/mem.

I was able to run 5 agents per instance successfully for parallel packer steps on a t3.medium.

**Comment by yob** [comment]
Good question!

The correct answer is very dependent on the way the agents are used, so we don't really have a recommendation. We default to 1 agent per instance because we don't know how much cpu/mem each customers build steps require.

Some steps are a bash script that deploy something, and 5 agents on a `t3.medium` will work fine. Other steps require a JVM with 16Gb of RAM, and even 1 agent on a `t3.medium` isn't going to work.

If 5 on a `t3.medium` works for your workload, that's great :+1:
