### ISSUE TITLE
UnfinishedJobsCount stuck at 4 with no jobs in queue

### ISSUE THREAD

**Issue by DanielHeath** [buildkite/elastic-ci-stack-for-aws#725]
Possibly because an instance got terminated and didn't shutdown cleanly? 

I'm not really clear on how, but I've got an elastic CI stack which is keeping an extra instance alive. Any idea where to look for this?

![image](https://user-images.githubusercontent.com/47430/94749799-08264380-03c8-11eb-9c07-d5047725dbad.png)

![image](https://user-images.githubusercontent.com/47430/94749819-15433280-03c8-11eb-91fd-74ad67d2e6c1.png)

**Comment by yob** [comment]
@DanielHeath which stack version are you running, and if it's v4.x is the `EnableExperimentalLambdaBasedAutoscaling` params enabled?

**Comment by DanielHeath** [comment]
EnableExperimentalLambdaBasedAutoscaling is disabled. Buildkite stack v4.5.0

**Comment by yob** [comment]
@DanielHeath I dug into this and it's totally a bug on our side. It should be back to 0 now, sorry about that.

If you're just experimenting with the elastic stack now, I recommend trialing `EnableExperimentalLambdaBasedAutoscaling`. It's described [here](https://forum.buildkite.community/t/experimental-lambda-based-scaler/425). It's been popular with those that've tried it (mostly because the scale up+down is faster and less disruptive), and it'll become the default in the upcoming v5 release (ETA: a week or two from now).

**Comment by DanielHeath** [comment]
Tried EnableExperimentalLambdaBasedAutoscaling. 

I'm still sometimes getting an instance left on all the time, even with no jobs queued.

**Comment by DanielHeath** [comment]
Possibly when the last build was cancelled instead of finishing?

**Comment by yob** [comment]
We have a bug in the canceling code atm that occasionally results in a job getting stuck in a `canceling` state, requiring us to manually transition it. You've been unlucky to get hit twice in two days.

The fix is running the review gauntlet now and I expect it'll reach prod tomorrow. Sorry!
