### ISSUE TITLE
Why is it not recommended to increase AgentsPerInstance ?

### ISSUE THREAD

**Issue by nitrocode** [buildkite/elastic-ci-stack-for-aws#759]
From the `README.md` of this repo

> While not enforced, it is highly recommended you also set your AgentsPerInstance value to 1.

It usually takes 2 to 3 min for the ASG to spin up a new EC2 and provision it before the agent can start taking more work so I'd imagine we'd want that parameter greater than 1 so why would it be recommended to keep it at 1?

**Comment by JuanitoFatas** [comment]
This was originally introduced in https://github.com/buildkite/elastic-ci-stack-for-aws/pull/523 and I think the reason is around agents shut down behaviors. For example:

- If an instance has 5 agents and 2 of them hits the idle timeout, then the instance left running with only 3 agents. So we will be paying more to per machine (need more CPU or Memory to run multiple agents), but may have less capacity. Not very cost effective.
- When machine got shut down, if there are multiple agents on one machine, they may not all sign off with Buildkite properly in the shut down window, agents ended up hanging.

/cc @matthewd because he may have more insights on this.

**Comment by lox** [comment]
This is outdated advice, as the stack used to install multiple instances of the agent. When we moved to spawning workers from the one agent we also improved the story around concurrency and idle termination.

**Comment by nitrocode** [comment]
@lox ah I see. Some of our members are hesitant to raise this parameter due to this warning. Thank you for clarifying.

Would it be ok to remove this section from the readme?

**Comment by niceking** [comment]
Issue closed by PR #760, thanks for the discussion everyone!
