### ISSUE TITLE
Format aws-stack.yml using yq so it's easier to transform and diff

### ISSUE THREAD

**Issue by nitrocode** [buildkite/elastic-ci-stack-for-aws#770]
To make it easier to diff the upstream stack yaml with a forked stack yaml, it would be nice to make the format of the `aws-stack.yml` formatted using `yq`.

For example, if I want to perform a transformation such as updating the description, I'll see a lot of changes.

```
✗ wget https://s3.amazonaws.com/buildkite-aws-stack/v5.0.1/aws-stack.yml
✗ yq w aws-stack.yml "Description" "$(yq r aws-stack.yml 'Description')-patched" > aws-stack.patched.yml
✗ diff -w aws-stack.yml aws-stack.patched.yml | wc -l
343
```

Most of those changes are all whitespace related.

I propose that the following is done for `aws-stack.yml` prior to it being committed/uploaded

```
yq r aws-stack.yml > aws-stack.yml.formatted
mv aws-stack.yml.formatted aws-stack.yml
```

**Comment by chloeruka** [comment]
I'd propose this is aligning to [YAML 1.2 spec](https://yaml.org/spec/1.2/spec.html) rather than specifically to yq's interpretation of it. This has totally been something that's tripped myself and @yob up recently in PRs. Most tooling, AWS examples and even the [YAML 1.2 spec](https://yaml.org/spec/1.2/spec.html#-%20block%20sequence%20entry//) indents block sequences beneath the node, but we don't. This was probably a deliberate attempt to reduce unnecessary indentation, but conforming to a style will help keep things more consistent and would be easy to automate/validate in source control.

One thing that would be nice to preserve blank lines just to provide some logical separation between elements. Our stack is something that is read as much as it is used, and this helps a lot with grokking what's going on in a very long file, particularly with some of Amazon's longer resources.

**Comment by nitrocode** [comment]
Hmmm yes that's true, the blank lines definitely make it more readable. Unfortunately, afaik, yq doesn't have this ability to maintain existing white lines (but maybe there is another tool that does).

Perhaps the code in the repo can stay as is and a new `aws-stack.formatted.yaml` file can be added to s3 alongside existing aws-stack.yml files? The new file would not have to be committed, just created from the original and copied over to s3. That would at least prevent having to maintain two files in the repo and still allow transformations with an expected diff.

**Comment by chloeruka** [comment]
That's fair, we could consider publishing a minified/formatted version. What if we standardised the indentation/hand-picked most of the YAML 1.2 spec adjustments (except the blank lines), would it still work for your purposes?

**Comment by chloeruka** [comment]
Although, at the point we're publishing a separate formatted version that's only been passed through yq, it might just be easier for the consumer of the stack to do it on their side as part of their tooling and then diff on that converted file

**Comment by nitrocode** [comment]
That's true. Thank you for looking into this!
