### ISSUE TITLE
Support add custom CIDR for SSh Ingress Security group rule

### ISSUE THREAD

**Issue by bhegazy** [buildkite/elastic-ci-stack-for-aws#787]
It will be good if we can create new parameter for example `SshIngressCidrIp` instead of hardcoded `0.0.0.0/0` in 
https://github.com/buildkite/elastic-ci-stack-for-aws/blob/master/templates/aws-stack.yml#L1081 

in our case we want to only allow ssh to agents from within our vpc Cidr

I can help create the PR when I'm free this week
 
Thanks!

**Comment by chloeruka** [comment]
Hi @bhegazy! Thanks for the suggestion. We're a bit hesitant to add more parameters to the stack, since it can already feel a little overwhelming for newcomers. As an alternative if you'd like security groups with custom ingress rules, I'd recommend setting the `SecurityGroupId` parameter in the stack to SGs you've made in your AWS account already – the one the stack creates is just there to help folks get started more easily.

**Comment by bhegazy** [comment]
Hi @chloeruka sounds reasonable, for our case we have terraform to run elastic-ci cf template so its easy to just include sg to module. However I think we should consider this option as well for anyone who just want to use the cf template directly, as it's not really a good practice to allow `22` `0.0.0.0/0` . Thank you!
