### ISSUE TITLE
BuildkiteAgentTokenParameterStorePath does not support multiple hierarchies in v5.3.0

### ISSUE THREAD

**Issue by mogggggg** [buildkite/elastic-ci-stack-for-aws#834]
Hi team!
As mentioned in [Slack](https://buildkite-community.slack.com/archives/C19BG77H9/p1619670223006000) the CloudFormation `AllowedPattern` regex was [changed](https://github.com/buildkite/elastic-ci-stack-for-aws/commit/630f8335d8085ceb55c0b048dcbbc34824994f4c) in v5.3.0 which has broken parameters using multiple hierarchies.

As an example our parameter used to be `/build/buildkite-agent-token` but we've had to update it to `/buildkite-agent-token` as part of the upgrade.

Not a huge issue for us, but I'm sure there will be other people affected 🙏

**Comment by yob** [comment]
I've tested the template from this branch with four different values in `BuildkiteAgentTokenParameterStorePath`:

1. `/foo` - passed validation
2. `/foo/bar` - passed validation
3. `foo` - failed validation
4. empty string - passed validation

**Comment by nitrocode** [comment]
Having the same issue...

```
Error: error updating CloudFormation stack (arn:aws:cloudformation:us-west-2:snip:stack/buildkite-sre/snip): ValidationError: Parameter 'BuildkiteAgentTokenParameterStorePath' must match pattern ^$|^/[a-zA-Z0-9_.-]+$
```

`BuildkiteAgentTokenParameterStorePath = /buildkite/agent_token`

It looks like this regex doesn't work because it needs an extra forward slash between the square brackets

Does not work with multiple hierarchies: `^$|^/[a-zA-Z0-9_.-]+$`
Does work with multiple hierarchies: `^$|^/[a-zA-Z0-9_.-/]+$`

See: https://regexr.com/5s4gk

**Comment by jufemaiz** [comment]
Apologies for missing this @yob ><
