### ISSUE TITLE
Upgrade from 5.5.1 up hangs on creation of the Autoscaling nested stack

### ISSUE THREAD

**Issue by glittershark** [buildkite/elastic-ci-stack-for-aws#938]
I'm trying to upgrade a stack from version 5.5.1 to 5.7.0 right now, and that upgrade is currently hanging on creating the nested `Autoscaling` stack. That stack just has the following two events in the "Events" log:

![image](https://user-images.githubusercontent.com/1481027/136222563-46873c8f-1fc9-453d-a8ba-7e60c7727560.png)

and no resources at all:

![image](https://user-images.githubusercontent.com/1481027/136222736-e9106053-8748-4768-b1e5-bd96047e2970.png)

**Comment by keithduncan** [comment]
Thank you for these details :bow:

I’m afraid I’ve been unable to reproduce this 🤔 would you be able to share your AWS Region and a redacted set of CloudFormation parameters for your stack?

> I'm not sure if it's "advanced" but the only potentially unusual thing we're doing is using a secretsmanager secret for the agent token

Are you using the SSM Reference Syntax to retrieve the Secrets Manager Secret value via SSM? I can’t see that causing CloudFormation deploy-time issues with the scaling Lambda because it is retrieved at [runtime](https://github.com/buildkite/buildkite-agent-scaler/blob/10a08588d7556c52a29dddb86ce1a6ae5c34fe37/lambda/main.go#L131).

> Just tried this, and it does seem to still stall.

I apologise again for the interruption, though I think this is good news in so far as the issue is reproducible 😅

**Comment by darrenwhighamfd** [comment]
Hi, Seeing this exact issue when trying to upgrade from 5.5.1 to 5.6.1 or 5.7.1. Tested deleting the stack and recreating and seeing the same issue with it hanging on the nested Autoscaling job, eventually errors with
2021-10-14 12:56:26 UTC+0100 Autoscaling CREATE_FAILED Embedded stack arn:aws:cloudformation:us-east-1:stack/buildkite-canary-Autoscaling-3349UQASS4SA/b19dfba0-2ce0-11ec-b434-1222c22090c1 was not successfully created: Internal Failure in the cloudformation events

**Comment by keithduncan** [comment]
@darrenwhighamfd could you share the event log for the Autoscaling sub-stack that fails to create successfully?

**Comment by keithduncan** [comment]
Other than any account level IAM restriction, do your AWS organisations use any [service control policies](https://docs.aws.amazon.com/organizations/latest/userguide/orgs_manage_policies_scps.html) that could be restricting access to the Serverless Application Repository?

**Comment by glittershark** [comment]
Also confirmed no service control policies

**Comment by darrenwhighamfd** [comment]
Hi @keithduncan,

I think the issue relates to the BuildkiteAgentTokenParameter trying to pull
from the secret manager, versus systems manager.

I asked our AWS support if they could shine a light. They believe the 
failure's due to the BuildkiteAgentTokenParameter having been defined as
`AWS::SSM::Parameter::Name`, which is a System Manager param, not Secret
Manager. 

The Secret Manager will encrypt the data, so GetParameter requires
'WithDecryption' to retrieve the value from Secret Manager. When our 
parameter type is `AWS::SSM::Parameter::Name`, CF doesn't include
WithDecryption in its GetParameter invocation, as
`AWS::SSM::Parameter::Name`, is a Systems Manager type. 

AWS Support recommended using Secrets Manager purely, and this dynamic
reference[1] below.

 Environment:
   Variables:
     BUILDKITE_AGENT_TOKEN_SSM_KEY: '{{resolve:secretsmanager:SecretName:SecretString:SecretKey}}'`

I've confirmed that the rest of the CF template works by deleting my stack and recreating fresh using the 
previous BuildkiteAgentTokenParameter option, and was able to install a
v5.7.1 stack. 

[1] https://docs.aws.amazon.com/AWSCloudFormation/latest/UserGuide/dynamic-references.html#dynamic-references-secretsmanager

**Comment by keithduncan** [comment]
That’s good research @darrenwhighamfd! We could be on to something as @glittershark also showed using AWS Secrets Manager SSM Parameter Store reference syntax.

> CF doesn't include WithDecryption in its GetParameter invocation

Our template _doesn’t_ resolve the value of the parameter, so this isn’t applicable. Instead the the template passes the value of the provided SSM Parameter Path to the EC2 instances via `UserData` and the scaling Lambda. Both resolve the value of this parameter at runtime.

The Lambda template [has both ssm:GetParameter and kms:Decrypt](https://github.com/buildkite/buildkite-agent-scaler/blob/77c6fe186c8585d815ea984b7223e45ca64da1b6/template.yaml#L120-L135) permissions, and passes [WithDecryption](https://github.com/buildkite/buildkite-agent-scaler/blob/77c6fe186c8585d815ea984b7223e45ca64da1b6/scaler/ssm.go#L9-L20) when fetching the value of the SSM parameter.

The launch template’s IAM Role [also has ssm:GetParameter and kms:Decrypt](https://github.com/buildkite/elastic-ci-stack-for-aws/blob/9596a11992fd8ba5eaef747b9f73be9111365264/templates/aws-stack.yml#L741-L761) permissions, and passes `WithDecryption` in both the [Linux](https://github.com/buildkite/elastic-ci-stack-for-aws/blob/9596a11992fd8ba5eaef747b9f73be9111365264/packer/linux/conf/bin/bk-install-elastic-stack.sh#L163) and [Windows](https://github.com/buildkite/elastic-ci-stack-for-aws/blob/9596a11992fd8ba5eaef747b9f73be9111365264/packer/windows/conf/bin/bk-install-elastic-stack.ps1#L119) install scripts.

I have previously tested and documented [AWS Secrets Manager SSM reference syntax](https://buildkite.com/docs/agent/v3/aws/secrets-manager) in our template.

> I've confirmed that the rest of the CF template works by deleting my stack and recreating fresh using the
previous BuildkiteAgentTokenParameter option, and was able to install a
v5.7.1 stack.

Were you passing a value for the `BuildkiteAgentTokenParameterStoreKMSKey` when using a secrets manager reference path for `BuildkiteAgentTokenParameterStorePath`? NB you must pass the Key ID, not the Key Name for this parameter.
